# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : RUNIX Soluções em Tecnologia
email      : contato@runix.net.br #this is also the email contact forms will go to
description: "Na RUNIX, somos especialistas em soluções de tecnologia da informação que garantem segurança, performance e alta disponibilidade para sua empresa. Atuamos com serviços estratégicos como backup inteligente, virtualização, hardening de sistemas, monitoramento e gerenciamento de infraestrutura, além de suporte técnico especializado. Nosso compromisso é proteger e otimizar seus ativos de TI, para que você possa focar no crescimento do seu negócio com tranquilidade e confiança. Com profissionais experientes e apaixonados por tecnologia, entregamos serviços sob medida, alinhados às melhores práticas do mercado, visando sempre eficiência, confiabilidade e inovação."
author     : Rony Muniz
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"

plugins:
  - jekyll-remote-theme
